/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.edu.utp.vista;

/**
 *
 * @author USUARIO
 */
public class LoginVista extends javax.swing.JFrame {

    public LoginVista() {
        setUndecorated(true);

        initComponents();
        setSize(800, 718);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    public javax.swing.JButton getBtnIngresar() {
        return btnIngresar;
    }

    public javax.swing.JButton getBtnRegistro() {
        return btnRegistro;
    }

    public javax.swing.JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    public javax.swing.JButton getBtnVolver() {
        return btnVolver;
    }

    public javax.swing.JButton getBtnSalir() {
        return btnSalir;
    }

    public javax.swing.JButton getBtnCerrar() {
        return btnCerrar;
    }

    public javax.swing.JLabel getLblDivision() {
        return lblDivision;
    }

    public javax.swing.JLabel getLblDivision1() {
        return lblDivision1;
    }

    public javax.swing.JLabel getLblNombreLogin() {
        return lblNombreLogin;
    }

    public javax.swing.JLabel getLblPassword() {
        return lblPassword;
    }

    public javax.swing.JLabel getLblFrase() {
        return lblFrase;
    }

    public javax.swing.JLabel getLblImgUser() {
        return lblImgUser;
    }

    public javax.swing.JLabel getLblNombre() {
        return lblNombre;
    }

    public javax.swing.JLabel getLblPasswordLogin() {
        return lblPasswordLogin;
    }

    public javax.swing.JLabel getLblConfirmPassword() {
        return lblConfirmPassword;
    }

    public javax.swing.JLabel getLblTitulo() {
        return lblTitulo;
    }
    
    public javax.swing.JLabel getLblTitulo1() {
        return lblTitulo1;
    }
    
    public javax.swing.JLabel getLblSlogan() {
        return lblSlogan;
    }
    
    public javax.swing.JLabel getLblImgHotel() {
        return lblImgHotel;
    }
    
    public javax.swing.JLabel getLblImgLogo() {
        return lblImgLogo;
    }

    public javax.swing.JPanel getPanelImagen() {
        return panelImagen;
    }

    public javax.swing.JPanel getPanelInfo() {
        return panelInfo;
    }

    public javax.swing.JPanel getPanelLogin() {
        return panelLogin;
    }

    public javax.swing.JPanel getPanelPrincipal() {
        return panelPrincipal;
    }

    public javax.swing.JPanel getPanelRegistro() {
        return panelRegistro;
    }
    
    public javax.swing.JPanel getPanelLogo() {
        return panelLogo;
    }
    
    public javax.swing.JScrollPane getScrollTxtDescripcion() {
        return scrollTxtDescripcion;
    }

    public javax.swing.JTabbedPane getTabbedFormularios() {
        return tabbedFormularios;
    }

    public javax.swing.JTextField getTxtNombreLogin() {
        return txtNombreLogin;
    }

    public javax.swing.JTextField getTxtNombre() {
        return txtNombre;
    }
    
    public javax.swing.JPasswordField getTxtPassword() {
        return txtPassword;
    }
    
    public javax.swing.JPasswordField getTxtPasswordLogin() {
        return txtPasswordLogin;
    }

    public javax.swing.JPasswordField getTxtConfirmPassword() {
        return txtConfirmPassword;
    }
    
    public javax.swing.JTextArea getTxtDescripcion() {
        return txtDescripcion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelImagen = new javax.swing.JPanel();
        panelLogo = new javax.swing.JPanel();
        lblImgLogo = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        lblSlogan = new javax.swing.JLabel();
        lblImgHotel = new javax.swing.JLabel();
        scrollTxtDescripcion = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        panelPrincipal = new javax.swing.JPanel();
        panelInfo = new javax.swing.JPanel();
        lblImgUser = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblFrase = new javax.swing.JLabel();
        tabbedFormularios = new javax.swing.JTabbedPane();
        panelLogin = new javax.swing.JPanel();
        lblNombreLogin = new javax.swing.JLabel();
        lblPasswordLogin = new javax.swing.JLabel();
        txtNombreLogin = new javax.swing.JTextField();
        txtPasswordLogin = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblDivision = new javax.swing.JLabel();
        panelRegistro = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblConfirmPassword = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();
        lblDivision1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelImagen.setMaximumSize(new java.awt.Dimension(400, 2147483647));
        panelImagen.setMinimumSize(new java.awt.Dimension(400, 548));
        panelImagen.setPreferredSize(new java.awt.Dimension(400, 548));
        panelImagen.setLayout(new java.awt.GridBagLayout());

        panelLogo.setName(""); // NOI18N
        panelLogo.setLayout(new java.awt.GridBagLayout());

        lblImgLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/imagen/LUMIERE_RESERVAS_100x100.png"))); // NOI18N
        lblImgLogo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        panelLogo.add(lblImgLogo, gridBagConstraints);

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo1.setText("LUMIÈRE RESERVAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(25, -5, 0, 25);
        panelLogo.add(lblTitulo1, gridBagConstraints);

        lblSlogan.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblSlogan.setForeground(new java.awt.Color(255, 255, 255));
        lblSlogan.setText("La excelencia, perfectamente reservada.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, -5, 0, 0);
        panelLogo.add(lblSlogan, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        panelImagen.add(panelLogo, gridBagConstraints);

        lblImgHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/imagen/img_hotel_fondo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, -5, 0, 0);
        panelImagen.add(lblImgHotel, gridBagConstraints);

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setRows(5);
        txtDescripcion.setText("Una aplicación de escritorio elegante y eficiente para \ngestionar reservas hoteleras con estilo y precisión. \nCon LUMIÈRE RESERVAS, los administradores podrán manejar \nhabitaciones, clientes y reservas de forma intuitiva, con una \ninterfaz moderna y herramientas integradas para optimizar \nla disponibilidad y la experiencia del huésped.");
        txtDescripcion.setFocusable(false);
        scrollTxtDescripcion.setViewportView(txtDescripcion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        panelImagen.add(scrollTxtDescripcion, gridBagConstraints);

        getContentPane().add(panelImagen);

        panelPrincipal.setMaximumSize(new java.awt.Dimension(400, 2147483647));
        panelPrincipal.setMinimumSize(new java.awt.Dimension(400, 462));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(400, 462));
        panelPrincipal.setLayout(new javax.swing.BoxLayout(panelPrincipal, javax.swing.BoxLayout.Y_AXIS));

        panelInfo.setMaximumSize(new java.awt.Dimension(2147483647, 300));
        panelInfo.setMinimumSize(new java.awt.Dimension(212, 300));
        panelInfo.setPreferredSize(new java.awt.Dimension(212, 300));
        panelInfo.setLayout(new java.awt.GridBagLayout());

        lblImgUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/utp/imagen/img_userlog.png"))); // NOI18N
        lblImgUser.setMaximumSize(new java.awt.Dimension(0, 200));
        lblImgUser.setMinimumSize(new java.awt.Dimension(0, 200));
        lblImgUser.setPreferredSize(new java.awt.Dimension(0, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelInfo.add(lblImgUser, gridBagConstraints);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Bienvenido a LUMIÈRE RESERVAS!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        panelInfo.add(lblTitulo, gridBagConstraints);

        lblFrase.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblFrase.setForeground(new java.awt.Color(51, 51, 51));
        lblFrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrase.setText("Inicia sesión en tu cuenta para continuar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelInfo.add(lblFrase, gridBagConstraints);

        panelPrincipal.add(panelInfo);

        panelLogin.setLayout(new java.awt.GridBagLayout());

        lblNombreLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombreLogin.setText("Nombre de usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 50);
        panelLogin.add(lblNombreLogin, gridBagConstraints);

        lblPasswordLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPasswordLogin.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 50);
        panelLogin.add(lblPasswordLogin, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 10, 50);
        panelLogin.add(txtNombreLogin, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 15, 50);
        panelLogin.add(txtPasswordLogin, gridBagConstraints);

        btnIngresar.setText("INICIAR SESIÓN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 75, 10, 75);
        panelLogin.add(btnIngresar, gridBagConstraints);

        btnRegistro.setText("REGISTRARSE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 75, 10, 75);
        panelLogin.add(btnRegistro, gridBagConstraints);

        btnSalir.setText("SALIR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 75, 0, 75);
        panelLogin.add(btnSalir, gridBagConstraints);

        lblDivision.setText("------------ ¿No tienes una cuenta? ------------");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panelLogin.add(lblDivision, gridBagConstraints);

        tabbedFormularios.addTab("Login", panelLogin);

        panelRegistro.setLayout(new java.awt.GridBagLayout());

        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombre.setText("Nombre de usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 50);
        panelRegistro.add(lblNombre, gridBagConstraints);

        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPassword.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 50);
        panelRegistro.add(lblPassword, gridBagConstraints);

        lblConfirmPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblConfirmPassword.setText("Confirmar contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 50);
        panelRegistro.add(lblConfirmPassword, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 10, 50);
        panelRegistro.add(txtNombre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 10, 50);
        panelRegistro.add(txtPassword, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 5, 50);
        panelRegistro.add(txtConfirmPassword, gridBagConstraints);

        btnRegistrar.setText("REGISTRARSE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 75, 10, 75);
        panelRegistro.add(btnRegistrar, gridBagConstraints);

        lblDivision1.setText("------------ ¿Ya tienes una cuenta? ------------");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panelRegistro.add(lblDivision1, gridBagConstraints);

        btnVolver.setText("VOLVER AL LOGIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 75, 10, 75);
        panelRegistro.add(btnVolver, gridBagConstraints);

        btnCerrar.setText("SALIR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 75, 0, 75);
        panelRegistro.add(btnCerrar, gridBagConstraints);

        tabbedFormularios.addTab("Registro", panelRegistro);

        panelPrincipal.add(tabbedFormularios);

        getContentPane().add(panelPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblDivision;
    private javax.swing.JLabel lblDivision1;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel lblImgHotel;
    private javax.swing.JLabel lblImgLogo;
    private javax.swing.JLabel lblImgUser;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordLogin;
    private javax.swing.JLabel lblSlogan;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JPanel panelImagen;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JScrollPane scrollTxtDescripcion;
    private javax.swing.JTabbedPane tabbedFormularios;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreLogin;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordLogin;
    // End of variables declaration//GEN-END:variables
}
